version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    networks:
      - appNetwork

  
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    networks:
      - appNetwork
    depends_on:
      - db
    command: >
      /bin/bash -c "poetry run alembic init migrations && cp env.py migrations/ &&
                    poetry run alembic revision --autogenerate -m 'Initial migration' &&
                    poetry run alembic upgrade head && poetry run uvicorn --host 0.0.0.0 --port 80 main:app --reload"

networks:
  appNetwork:
