name: pasha_insurance
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.2.1+1
  stomp_dart_client: ^0.4.4
  hydrated_bloc: ^9.1.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  get_it: ^7.6.0
  flutter_dotenv: ^5.1.0
  path_provider: ^2.0.15
  mask_text_input_formatter: ^2.4.0
  either_dart: ^1.0.0
  logger: ^1.4.0
  fluttertoast: ^8.2.2
  get_storage: ^2.1.1
  flutter_scale_tap: ^1.0.5
  after_layout: ^1.2.0
  go_router: ^10.0.0
  flutter_svg: ^2.0.7
  intl: ^0.18.1
  provider: ^6.1.1
  image_picker: ^1.0.4
  http_parser: ^4.0.2
  google_maps_flutter: ^2.5.0
  location: ^5.0.3
  geolocator: ^10.1.0
  permission_handler: ^11.0.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true

  assets:
    - .env
    - assets/fonts/
    - assets/images/
    - assets/icons/

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/OpenSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
